import Layout from "@/components/layout/Layout";
import Shop from "@/components/sections/Shop";
import { getCarousel } from "@/lib/data/carousel";
import Slider1 from "@/components/sections/Slider1";
import { filterProducts } from "@/lib/data/products";
import DealProduct1 from "@/components/sections/DealProduct1";
import ProductCatalog from "@/components/sections/ProductCatalog";

export const metadata = {
  title: "Ninico - Minimal NextJS React Template",
  description: "Generated by create next app",
};

export default async function Home() {
  const carousel = await getCarousel();
  // const categories = await listCategories();
  const initialProducts = await filterProducts({
    q: "",
    minPrice: "0",
    maxPrice: "10000",
    category_handle: "all",
    pageParam: 1,
  });

  return (
    <>
      <Layout headerStyle={1} footerStyle={1}>
        <Slider1 carousels={carousel} />
        {/* <Category categories={categories} /> */}
        <ProductCatalog initialProducts={initialProducts} />
        <DealProduct1 />
        <Shop />
      </Layout>
    </>
  );
}
