name: Auto Deploy to EC2 (Backend Only)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'          # Only trigger when files in /backend change
      - '.github/workflows/**'  # (Optional) Allow workflow updates to trigger too

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/reliablecreations
            git pull origin main
            chmod +x run.sh
            ./run.sh
